import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Script } from 'node:vm';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.slice(2).includes('--check');
if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('Usage: node scripts/build.mjs [--check]');
const catalog = JSON.parse(readFileSync(resolve(root, 'catalog.json'), 'utf8'));
if (!/^[a-z\d](?:[a-z\d-]*[a-z\d])?$/i.test(catalog.owner) || !/^[\w.-]+$/.test(catalog.repository)) {
  throw new Error('Set a valid GitHub owner and repository name in catalog.json.');
}
const repoURL = `https://github.com/${catalog.owner}/${catalog.repository}`;
const siteURL = `https://${catalog.owner}.github.io/${catalog.repository}/`;
const escapeHTML = text => String(text).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const escapeCell = text => String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const ids = new Set();
const items = catalog.bookmarklets.map(item => {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(item.id) || ids.has(item.id)) throw new Error('Invalid or duplicate bookmarklet id');
  ids.add(item.id);
  for (const field of ['name', 'summary', 'usage', 'note']) if (typeof item[field] !== 'string' || !item[field]) throw new Error(`${item.id}: missing ${field}`);
  const source = readFileSync(resolve(root, `src/${item.id}.js`), 'utf8').trim();
  new Script(source, { filename: `src/${item.id}.js` });
  // Encode every source newline, quote and URL fragment. Keep the readable source
  // intact; no minifier or third-party dependency is needed. void prevents a
  // bookmarklet's result from replacing the current document.
  const url = 'javascript:void%20' + encodeURIComponent(source).replace(/[!'()*]/g, char => '%' + char.charCodeAt(0).toString(16).toUpperCase());
  new Script(decodeURIComponent(url.slice('javascript:'.length)));
  return { ...item, url };
});

const readme = `<!-- Generated by scripts/build.mjs. Edit catalog.json, src/ or the builder, then regenerate. -->
# Bookmarklets

Small browser tools for capturing site icons, generating passphrases, copying Halo ticket links, tidying Rhea and opening pages at a chosen window size.

**[Open the bookmarklet install page](${siteURL})** — drag a bookmarklet button from that page to your bookmarks bar.

The install link becomes available after GitHub Pages is enabled. This bundle assumes **${catalog.owner}/${catalog.repository}**; if you use a different repo, update \`owner\` and \`repository\` in [catalog.json](catalog.json) and run \`npm run build\` before uploading.

## Bookmarklets

| Bookmarklet | Overview | Install |
| --- | --- | --- |
${items.map(item => `| ${escapeCell(item.name)} | ${escapeCell(item.summary)} | [Install](${siteURL}#${item.id}) |`).join('\n')}

## Install

1. Show your browser's bookmarks bar. In Chrome or Edge on Windows, press **Ctrl + Shift + B**.
2. Open the install page above.
3. Drag the named bookmarklet button to the bookmarks bar.
4. Open the webpage you want to work on and click the saved bookmarklet.

**GitHub README limitation:** GitHub strips executable \`javascript:\` links from rendered Markdown. The README's Install links therefore open the relevant section of the HTML install page; drag the button there, rather than the README link. See [GitHub's bookmarklet issue](https://github.com/github/markup/issues/79).

**Without hosting:** download or clone the repo, open [docs/index.html](docs/index.html) locally in a browser and drag the buttons. Opening the HTML file in GitHub's code viewer does not render the installer.

**Manual installation:** use **Copy bookmarklet URL** on the install page, create or edit a bookmark, and paste into its URL/address field. Each [dist/*.bookmarklet.txt](dist/) file contains the same single-line URL. Paste into the bookmark editor, rather than the address bar, which may strip the \`javascript:\` prefix.

**Bulk installation:** import [bookmarks.html](bookmarks.html) through your browser's bookmark manager. It adds a folder containing all five bookmarklets; move them to your bookmarks bar if needed.

## Usage notes

${items.map(item => `### ${item.name}\n\n${item.usage}\n\n${item.note}\n\n[Readable source](src/${item.id}.js) · [Bookmarklet URL](dist/${item.id}.bookmarklet.txt)${item.upstream ? ` · [Original project](${item.upstream})` : ''}`).join('\n\n')}

Bookmarklets run in the active webpage. Built-in browser pages, some document viewers and sites with restrictive content policies may prevent them from running. These tools use native browser APIs and do not load external scripts. Logo Grab requests the current site's declared icons and manifest.

## Publish the install page with GitHub Pages

1. Add this bundle's contents to your repo root and commit them to \`main\`.
2. In the repo, open **Settings → Pages**.
3. Under **Build and deployment**, set **Source** to **Deploy from a branch**.
4. Choose **main**, select the **/docs** folder, and click **Save**.
5. Wait for deployment to finish, then open the URL shown by GitHub.

The page consists of plain HTML with embedded CSS and JavaScript. No build workflow is needed for hosting: the generated files are already included. [GitHub Pages publishing instructions](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

## Maintain the repo

Requires **Node.js 20 or later** only when regenerating files. No package installation is required.

1. Edit a file in \`src/\` to change a bookmarklet.
2. Edit \`catalog.json\` to change names, descriptions or the repo address.
3. Run \`npm run build\` to update the README, install page, bookmark import file and encoded URLs.
4. Run \`npm run check\` to validate JavaScript syntax and verify that generated files match their sources.
5. Commit the source and generated files together. After code changes, users must re-drag or re-import affected bookmarklets; saved bookmarks do not update automatically.

| File | Purpose |
| --- | --- |
| \`README.md\` | Overview, installation and maintenance instructions |
| \`docs/index.html\` | Self-contained page with draggable bookmarklet links and copy buttons |
| \`docs/.nojekyll\` | Serves the install page directly on GitHub Pages |
| \`bookmarks.html\` | Browser bookmark import file |
| \`src/*.js\` | Readable JavaScript for each bookmarklet |
| \`dist/*.bookmarklet.txt\` | Ready-to-paste, single-line bookmarklet URLs |
| \`catalog.json\` | Descriptions and GitHub repo address |
| \`scripts/build.mjs\` | Dependency-free generator and consistency check |
| \`package.json\` | Build and check shortcuts |
| \`CHANGES.md\` | Small corrections made while packaging the supplied code |

The Passphrases bookmarklet is a local copy of the supplied code associated with [passphraseGenerator](https://github.com/danlibbo/passphraseGenerator); it is not automatically synchronised with that project. Its wordlists and generation algorithm are retained.
`;

const cards = items.map(item => `<article id="${item.id}">
  <div class="card-heading"><span class="number">${String(items.indexOf(item) + 1).padStart(2, '0')}</span><h2>${escapeHTML(item.name)}</h2></div>
  <p class="summary">${escapeHTML(item.summary)}</p>
  <div class="tools"><a class="bookmarklet" draggable="true" href="${escapeHTML(item.url)}" aria-describedby="drag-help">${escapeHTML(item.name)}</a><button type="button" class="copy" data-bookmarklet="${item.id}">Copy bookmarklet URL</button></div>
  <p>${escapeHTML(item.usage)}</p>
  <details><summary>Details and manual installation</summary><p>${escapeHTML(item.note)}</p><label for="url-${item.id}">Bookmark URL</label><textarea id="url-${item.id}" readonly spellcheck="false" rows="3">${escapeHTML(item.url)}</textarea><p class="links"><a href="${repoURL}/blob/main/src/${item.id}.js">Readable source</a>${item.upstream ? ` · <a href="${escapeHTML(item.upstream)}">Original project</a>` : ''}</p></details>
</article>`).join('\n');

const html = `<!doctype html>
<!-- Generated by scripts/build.mjs. -->
<html lang="en-AU">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Install five useful browser bookmarklets by dragging them to your bookmarks bar."><title>Bookmarklets — drag to install</title>
<style>
:root{color-scheme:light;--ink:#182c37;--muted:#536976;--accent:#005e58;--line:#ccd8de}*{box-sizing:border-box}body{margin:0;background:#f3f6f5;color:var(--ink);font:16px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:var(--accent);text-underline-offset:3px}button,textarea{font:inherit}button,a,summary{-webkit-tap-highlight-color:transparent}:focus-visible{outline:3px solid #bf7700;outline-offset:4px}main{max-width:1080px;margin:auto;padding:52px 24px 36px}.eyebrow{font-size:12px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:var(--accent)}h1{font-size:clamp(34px,5vw,58px);line-height:1.1;letter-spacing:-2px;margin:12px 0 16px}header>p{max-width:720px;font-size:18px;color:var(--muted)}.instructions{display:flex;gap:20px;align-items:center;background:#e1ece8;border:1px solid #c5d9d2;border-radius:12px;padding:18px 24px;margin:28px 0 32px}.instructions strong{white-space:nowrap}.instructions p{margin:0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}article{background:white;border:1px solid var(--line);border-radius:14px;padding:26px;scroll-margin-top:24px}article:target{outline:3px solid #8abeb6;outline-offset:3px}.card-heading{display:flex;gap:12px;align-items:center}.number{font:12px ui-monospace,monospace;color:var(--muted);border:1px solid var(--line);border-radius:6px;padding:3px 7px}h2{font-size:22px;line-height:1.3;margin:0}.summary{color:var(--muted);min-height:78px;margin:16px 0}.tools{display:flex;align-items:center;flex-wrap:wrap;gap:12px;margin-bottom:20px}.bookmarklet{display:inline-block;padding:10px 16px;border:1px solid var(--accent);border-radius:8px;background:var(--accent);color:white;font-size:15px;font-weight:650;text-decoration:none;cursor:grab;box-shadow:0 2px 0 #003e39}.bookmarklet:active{cursor:grabbing}.bookmarklet:hover{background:#004e49}.copy{border:1px solid var(--line);border-radius:8px;background:white;padding:10px 12px;font-size:13px;color:var(--ink);cursor:pointer}.copy:hover{background:#edf3f1}article>p:not(.summary){font-size:14px;color:var(--muted)}details{border-top:1px solid var(--line);padding-top:14px;font-size:14px}summary{font-weight:600;cursor:pointer}details label{display:block;font-weight:600}textarea{display:block;width:100%;padding:10px;margin-top:6px;border:1px solid var(--line);border-radius:6px;background:#f6f8f8;color:var(--ink);font:12px/1.5 ui-monospace,monospace;resize:vertical;overflow-wrap:anywhere}footer{margin-top:30px;font-size:13px;color:var(--muted)}#status{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#182c37;color:white;max-width:calc(100vw - 32px);padding:12px 20px;border-radius:10px;box-shadow:0 4px 20px #0002;z-index:100;pointer-events:none}#status:empty{display:none}@media(max-width:740px){main{padding:30px 16px}.grid{grid-template-columns:1fr}.instructions{display:block;padding:16px}.instructions strong{display:block;margin-bottom:6px}.summary{min-height:0}article{padding:22px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
</style></head>
<body><main>
<header><span class="eyebrow">A small browser toolkit</span><h1>One bookmark. One useful job.</h1><p>Five tools for everyday tasks. Drag a button to your bookmarks bar, then run it on the page you're working on.</p></header>
<div class="instructions" id="drag-help"><strong>Drag to install →</strong><p>Show your bookmarks bar with <strong>Ctrl + Shift + B</strong> in Chrome or Edge on Windows. Drag a green button below onto the bar. Clicking it here shows instructions.</p></div>
<div class="grid">${cards}</div>
<footer><p>Can't drag? Copy a bookmarklet URL and paste it into a bookmark's URL field. Bookmarklets run in the active page; browser pages and restrictive site policies can block them.</p><p><a href="${repoURL}">GitHub repo &amp; README</a> · Generated from readable JavaScript, with no external scripts or tracking.</p></footer>
</main><div id="status" role="status" aria-live="polite"></div>
<script>
(() => {
  const status = document.getElementById('status');
  let timer;
  function announce(message) { status.textContent = message; clearTimeout(timer); timer = setTimeout(() => { status.textContent = ''; }, 6000); }
  document.querySelectorAll('.bookmarklet').forEach(link => link.addEventListener('click', event => { event.preventDefault(); announce('Drag this button to your bookmarks bar, or use Copy bookmarklet URL.'); }));
  document.querySelectorAll('.copy').forEach(button => button.addEventListener('click', async () => {
    const card = document.getElementById(button.dataset.bookmarklet);
    const url = card.querySelector('.bookmarklet').getAttribute('href');
    try {
      if (!navigator.clipboard?.writeText) throw new Error('Use manual copy');
      await navigator.clipboard.writeText(url);
      announce('Bookmarklet URL copied. Paste it into a bookmark’s URL field.');
    } catch (error) {
      card.querySelector('details').open = true;
      const field = card.querySelector('textarea');
      field.focus(); field.select();
      announce('URL selected. Press Ctrl+C (or Command+C) and paste into a bookmark’s URL field.');
    }
  }));
})();
</script></body></html>
`;

const bookmarks = `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- Generated by scripts/build.mjs. Import using your browser's bookmark manager. -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarklets</TITLE>
<H1>Bookmarklets</H1>
<DL><p>
  <DT><H3>Bookmarklets</H3>
  <DL><p>
${items.map(item => `    <DT><A HREF="${escapeHTML(item.url)}">${escapeHTML(item.name)}</A>\n    <DD>${escapeHTML(item.summary)}`).join('\n')}
  </DL><p>
</DL><p>
`;

const outputs = new Map([
  ['README.md', readme], ['docs/index.html', html], ['bookmarks.html', bookmarks],
  ...items.map(item => [`dist/${item.id}.bookmarklet.txt`, item.url + '\n'])
]);
let failed = false;
for (const [path, contents] of outputs) {
  const destination = resolve(root, path);
  if (check) {
    if (!existsSync(destination) || readFileSync(destination, 'utf8') !== contents) {
      console.error(`Out of date: ${path}`);
      failed = true;
    }
  } else {
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, contents);
  }
}
if (failed) { console.error('Run npm run build and commit the generated files.'); process.exitCode = 1; }
else console.log(`${check ? 'Verified' : 'Generated'} ${outputs.size} files for ${items.length} bookmarklets. Install page: ${siteURL}`);
